import type { Metadata } from "next";
import Link from "next/link";
import { BRAND, NON_CLINICAL_BOUNDARY } from "@/lib/product/brand";

export const metadata: Metadata = {
  title: `Terms — ${BRAND.name}`,
  description: `The terms of using ${BRAND.name}.`,
};

/**
 * Terms of service.
 *
 * Linked from the footer since the first landing page; the route did not
 * exist. Plain-language and honest about what the product is. Not legal
 * advice — review before a public launch.
 */
export default function TermsPage() {
  return (
    <div className="lp">
      <header className="lp-nav">
        <Link href="/" className="lp-brand">
          <span className="lp-brand-name">{BRAND.name}</span>
        </Link>
      </header>

      <main className="lp-section lp-legal">
        <h1 className="lp-h1" style={{ fontSize: "clamp(1.8rem, 4vw, 2.4rem)" }}>
          Terms
        </h1>
        <p className="lp-body">Last updated: {new Date().getFullYear()}</p>

        <h2>What this is</h2>
        <p className="lp-body">
          {BRAND.name} is a coaching tool for planning and follow-through, built around a
          daily reading of your mental state. {NON_CLINICAL_BOUNDARY} If you are in crisis or
          need clinical care, contact a qualified professional or your local emergency
          services.
        </p>

        <h2>Your account</h2>
        <p className="lp-body">
          You are responsible for keeping your login details secure and for what happens
          under your account. One account per person.
        </p>

        <h2>What the coach says</h2>
        <p className="lp-body">
          Responses are generated by a language model. They can be wrong. Treat them as a
          prompt to think, not as instruction — particularly on anything medical, legal or
          financial, where you should consult someone qualified.
        </p>

        <h2>Fair use</h2>
        <p className="lp-body">
          There are daily limits on coach conversations and plan generation, because each one
          costs real money to run. We will tell you when you reach one. Do not use the
          service to harass anyone, to generate harmful content, or to attempt to extract the
          underlying models.
        </p>

        <h2>Availability</h2>
        <p className="lp-body">
          The product is in beta and free. We do not guarantee uptime, and features may
          change. We will give notice before anything that would lose your data.
        </p>

        <h2>Ending it</h2>
        <p className="lp-body">
          You can delete your account at any time from Settings, which permanently removes
          your data. We may suspend an account that breaks these terms.
        </p>
      </main>

      <footer className="lp-footer">
        <div className="lp-footer-row">
          <span>
            © {new Date().getFullYear()} {BRAND.name}
          </span>
          <nav aria-label="Footer">
            <Link href="/">Home</Link>
            <Link href="/privacy">Privacy</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
