-- ================================================================
-- FIX: Add missing columns to tasks table
-- This migration adds goal_id and other missing columns that may
-- not exist if migrations ran in a different order
-- ================================================================

-- Add goal_id column if it doesn't exist
ALTER TABLE public.tasks 
  ADD COLUMN IF NOT EXISTS goal_id UUID REFERENCES public.goals(id) ON DELETE SET NULL;

-- Add priority column if it doesn't exist
ALTER TABLE public.tasks 
  ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high'));

-- Add auto_generated column if it doesn't exist
ALTER TABLE public.tasks 
  ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT false;

-- Add generation_reason column if it doesn't exist
ALTER TABLE public.tasks 
  ADD COLUMN IF NOT EXISTS generation_reason TEXT;

-- Add updated_at column if it doesn't exist
ALTER TABLE public.tasks 
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Ensure indexes exist
CREATE INDEX IF NOT EXISTS idx_tasks_goal ON public.tasks(goal_id);
CREATE INDEX IF NOT EXISTS idx_tasks_auto_gen ON public.tasks(user_id, auto_generated, due_date) WHERE auto_generated = true;
CREATE INDEX IF NOT EXISTS idx_tasks_user_status_date ON public.tasks(user_id, status, due_date);

-- Ensure the trigger for updated_at exists
DROP TRIGGER IF EXISTS update_tasks_updated_at ON public.tasks;
CREATE TRIGGER update_tasks_updated_at 
  BEFORE UPDATE ON public.tasks 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON COLUMN public.tasks.goal_id IS 'Optional reference to a goal this task contributes to';
COMMENT ON COLUMN public.tasks.priority IS 'Task priority level';
COMMENT ON COLUMN public.tasks.auto_generated IS 'Whether this task was auto-generated by the system';
COMMENT ON COLUMN public.tasks.generation_reason IS 'Reason for auto-generation (e.g., daily_auto_generation)';
